---
name: "pages-build-integration"

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "README.md"
      - ".github/workflows/pages-build-integration.yml"

defaults:
  run:
    shell: "bash -l {0}"

concurrency:
  group: "pages-build-integration"
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  pages-build-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        with:
          fetch-depth: 0

      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@1f0c5cde4bc74cd7e1254d0cb4de8d49e9068c7d
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          enablement: true

      - name: Install dependencies
        uses: mamba-org/setup-micromamba@422500192359a097648154e8db4e39bdb6c6eed7
        with:
          micromamba-version: "latest"
          environment-file: "docs/mkdocs-environment.yml"
          init-shell: bash
          cache-environment: true

      - name: Build site
        run: mkdocs build
        shell: bash -el {0}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa
        with:
          path: site

#      - name: Deploy Docs
#        env:
#          MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.GITHUB_TOKEN }}
#        run: mkdocs gh-deploy --force -v
#        shell: bash -el {0}

  pages-build-deployment:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: pages-build-integration
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@decdde0ac072f6dcbe43649d82d9c635fff5b4e4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
