---
name: "pages-build-integration"

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "README.md"
      - ".github/workflows/pages-build-integration.yml"

defaults:
  run:
    shell: "bash -l {0}"

concurrency:
  group: "pages-build-integration"
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

env:
  MICROMAMBA_VERSION: "latest"

jobs:
  pages-build-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        with:
          fetch-depth: 0

      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@1f0c5cde4bc74cd7e1254d0cb4de8d49e9068c7d
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        uses: "mamba-org/setup-micromamba@v1"
        with:
          micromamba-version: "${{ env.MICROMAMBA_VERSION }}"
          environment-file: "docs/mkdocs-environment.yml"
          init-shell: bash
          cache-environment: true

      - name: Build site
        run: mkdocs build
        shell: bash -el {0}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
          token: ${{ secrets.GITHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

     # - name: Deploy Docs
     #   env:
     #     MKDOCS_GIT_COMMITTERS_APIKEY: ${{ secrets.GITHUB_TOKEN }}
     #   run: mkdocs gh-deploy --force
     #   shell: bash -el {0}

  pages-build-deployment:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: pages-build-integration
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
